; SPDX-FileCopyrightText: 2026 Yuma Kakei <yumasansansan@gmail.com>
; SPDX-License-Identifier: GPL-3.0-or-later
;
; This file is part of ADLplug-Next. The SPDX lines name its copyright holder
; and its license, in the machine-readable form of the REUSE specification: the
; GNU General Public License, version 3 or any later version
; (LICENSES/GPL-3.0-or-later.txt).
;
; The instrument banks of the OPN2 plugin, which tools/bankgen packs when the
; plugin is built. The list has the form of libADLMIDI's banks.ini. Each bank
; gives its format and its file: WOPN, or GYB or GEMS, which tools/bankgen
; converts as OPN2 Bank Editor reads them. It may also name a text on the bank
; (info), a license text that its sources leave out (license), and add a note
; (note). Paths are relative to the source tree. The plugin starts with the
; first bank.
;
; The banks marked greyzone, for which no license or permission of their
; authors is known, are left out unless the plugin is built with
; ADLplug_GREYZONE_BANKS, like the banks of libADLMIDI's grey zone. The others
; have known terms: the MIT License for the XG, DMXOPN2 and old GM banks, and
; the BSD 3-Clause License for fmmidi.

[General]
banks = 10

[bank-0]
name     = "WOPN (XG bank by Wohlstand)"
format   = WOPN
file     = "thirdparty/libOPNMIDI/fm_banks/xg.wopn"
info     = "thirdparty/libOPNMIDI/fm_banks/readme.txt"

[bank-1]
name     = "WOPN (DMXOPN2 bank by Papiezak and Sneakernets)"
format   = WOPN
file     = "thirdparty/libOPNMIDI/fm_banks/gs-by-papiezak-and-sneakernets.wopn"
info     = "thirdparty/libOPNMIDI/fm_banks/gs-by-papiezak-and-sneakernets-readme.txt"
license  = "resources/opn2/LICENSE-DMXOPN2.txt"
note     = "The license below is that of the DMXOPN2 repository that the readme names, https://github.com/sneakernets/DMXOPN2."

[bank-2]
name     = "WOPN (fmmidi)"
format   = WOPN
file     = "thirdparty/libOPNMIDI/fm_banks/fmmidi.wopn"
info     = "thirdparty/libOPNMIDI/fm_banks/fmmidi-readme.txt"

[bank-3]
name     = "GYB (WinFM)"
format   = GYB
file     = "thirdparty/OPN2BankEditor/Bank_Examples/GYB-nineko/Instruments_WinFM.gyb"
greyzone = true

[bank-4]
name     = "WOPN (MIDI2VGM)"
format   = WOPN
file     = "thirdparty/libOPNMIDI/fm_banks/Nineko.wopn"
info     = "thirdparty/libOPNMIDI/fm_banks/Nineko-readme.txt"
greyzone = true

[bank-5]
name     = "GEMS (GEMS FMLib) :NON-GM:"
format   = GEMS
file     = "thirdparty/OPN2BankEditor/Bank_Examples/GEMS-FMLib/patch.bnk"
note     = "libOPNMIDI's fm_banks/gems-fmlib-gmize-readme.txt describes this set as the instruments that came with GEMS, the music creation system of Sega."
greyzone = true

[bank-6]
name     = "GEMS (GEMS Ship) :NON-GM:"
format   = GEMS
file     = "thirdparty/OPN2BankEditor/Bank_Examples/GEMS-Ship/patch.bnk"
greyzone = true

[bank-7]
name     = "WOPN (GEMS GM (Modded by Wohlstand))"
format   = WOPN
file     = "thirdparty/libOPNMIDI/fm_banks/gems-fmlib-gmize.wopn"
info     = "thirdparty/libOPNMIDI/fm_banks/gems-fmlib-gmize-readme.txt"
greyzone = true

[bank-8]
name     = "WOPN (TomSoft SegaMusic (Modded by Wohlstand))"
format   = WOPN
file     = "thirdparty/libOPNMIDI/fm_banks/Tomsoft.wopn"
info     = "thirdparty/libOPNMIDI/fm_banks/Tomsoft-readme.txt"
greyzone = true

[bank-9]
name     = "WOPN (Old GM bank by Wohlstand)"
format   = WOPN
file     = "thirdparty/libOPNMIDI/fm_banks/gm-old.wopn"
info     = "thirdparty/libOPNMIDI/fm_banks/readme.txt"
note     = "libOPNMIDI's commit 7bae872 (2019-01-11) renamed this bank from fm_banks/gm.wopn, of which the readme below speaks, and made gm.wopn a link to xg.wopn."
