//          Copyright Jean Pierre Cimalando 2018.
// Distributed under the Boost Software License, Version 1.0.
//    (See accompanying file LICENSE or copy at
//          http://www.boost.org/LICENSE_1_0.txt)
//
// SPDX-FileCopyrightText: 2018 Jean Pierre Cimalando
// SPDX-FileCopyrightText: 2026 Yuma Kakei <yumasansansan@gmail.com>
// SPDX-License-Identifier: BSL-1.0 AND GPL-3.0-or-later
//
// This file comes from ADLplug and was modified for ADLplug-Next. The notice at
// the top is ADLplug's; the LICENSE it names was ADLplug's copy of the Boost
// Software License, now LICENSES/BSL-1.0.txt. The SPDX lines name the copyright
// holders and licenses in the machine-readable form of the REUSE specification:
// ADLplug's code is under the Boost Software License 1.0, and ADLplug-Next's
// changes are under the GNU General Public License, version 3 or any later
// version (LICENSES/GPL-3.0-or-later.txt).

#include "insnames.h"

const char *midi_spec_name(Midi_Spec spec)
{
    switch (spec) {
    case Midi_Spec::GM: return "GM";
    case Midi_Spec::GS: return "GS";
    case Midi_Spec::SC88: return "SC88";
    case Midi_Spec::MT32: return "MT32";
    case Midi_Spec::XG: return "XG";
    }
    return nullptr;
}

const Midi_Db &midi_db()
{
    static const Midi_Db db;
    return db;
}

Midi_Db::Midi_Db()
{
    init_midi_inst();
    init_midi_perc();
    init_midi_ex();
}

void Midi_Db::init_midi_inst()
{
    midi_inst_[0] = "Acoustic Grand Piano";
    midi_inst_[1] = "Bright Acoustic Piano";
    midi_inst_[2] = "Electric Grand Piano";
    midi_inst_[3] = "Honky-Tonk Piano";
    midi_inst_[4] = "Rhodes Piano";
    midi_inst_[5] = "Chorused Piano";
    midi_inst_[6] = "Harpsichord";
    midi_inst_[7] = "Clavinet";
    midi_inst_[8] = "Celesta";
    midi_inst_[9] = "Glockenspiel";
    midi_inst_[10] = "Music box";
    midi_inst_[11] = "Vibraphone";
    midi_inst_[12] = "Marimba";
    midi_inst_[13] = "Xylophone";
    midi_inst_[14] = "Tubular Bells";
    midi_inst_[15] = "Dulcimer";
    midi_inst_[16] = "Hammond Organ";
    midi_inst_[17] = "Percussive Organ";
    midi_inst_[18] = "Rock Organ";
    midi_inst_[19] = "Church Organ";
    midi_inst_[20] = "Reed Organ";
    midi_inst_[21] = "Accordion";
    midi_inst_[22] = "Harmonica";
    midi_inst_[23] = "Tango Accordion";
    midi_inst_[24] = "Acoustic Guitar (nylon)";
    midi_inst_[25] = "Acoustic Guitar (steel)";
    midi_inst_[26] = "Electric Guitar (jazz)";
    midi_inst_[27] = "Electric Guitar (clean)";
    midi_inst_[28] = "Electric Guitar (muted)";
    midi_inst_[29] = "Overdrive Guitar";
    midi_inst_[30] = "Distortion Guitar";
    midi_inst_[31] = "Guitar Harmonics";
    midi_inst_[32] = "Acoustic Bass";
    midi_inst_[33] = "Electric Bass (finger)";
    midi_inst_[34] = "Electric Bass (pick)";
    midi_inst_[35] = "Fretless Bass";
    midi_inst_[36] = "Slap Bass 1";
    midi_inst_[37] = "Slap Bass 2";
    midi_inst_[38] = "Synth Bass 1";
    midi_inst_[39] = "Synth Bass 2";
    midi_inst_[40] = "Violin";
    midi_inst_[41] = "Viola";
    midi_inst_[42] = "Cello";
    midi_inst_[43] = "Contrabass";
    midi_inst_[44] = "Tremolo Strings";
    midi_inst_[45] = "Pizzicato String";
    midi_inst_[46] = "Orchestral Harp";
    midi_inst_[47] = "Timpany";
    midi_inst_[48] = "String Ensemble 1";
    midi_inst_[49] = "String Ensemble 2";
    midi_inst_[50] = "Synth Strings 1";
    midi_inst_[51] = "Synth Strings 2";
    midi_inst_[52] = "Choir Aahs";
    midi_inst_[53] = "Voice Oohs";
    midi_inst_[54] = "Synth Voice";
    midi_inst_[55] = "Orchestra Hit";
    midi_inst_[56] = "Trumpet";
    midi_inst_[57] = "Trombone";
    midi_inst_[58] = "Tuba";
    midi_inst_[59] = "Muted Trumpet";
    midi_inst_[60] = "French Horn";
    midi_inst_[61] = "Brass Section";
    midi_inst_[62] = "Synth Brass 1";
    midi_inst_[63] = "Synth Brass 2";
    midi_inst_[64] = "Soprano Sax";
    midi_inst_[65] = "Alto Sax";
    midi_inst_[66] = "Tenor Sax";
    midi_inst_[67] = "Baritone Sax";
    midi_inst_[68] = "Oboe";
    midi_inst_[69] = "English Horn";
    midi_inst_[70] = "Bassoon";
    midi_inst_[71] = "Clarinet";
    midi_inst_[72] = "Piccolo";
    midi_inst_[73] = "Flute";
    midi_inst_[74] = "Recorder";
    midi_inst_[75] = "Pan Flute";
    midi_inst_[76] = "Bottle Blow";
    midi_inst_[77] = "Shakuhachi";
    midi_inst_[78] = "Whistle";
    midi_inst_[79] = "Ocarina";
    midi_inst_[80] = "Lead 1 (Square)";
    midi_inst_[81] = "Lead 2 (Sawtooth)";
    midi_inst_[82] = "Lead 3 (Calliope)";
    midi_inst_[83] = "Lead 4 (Chiff)";
    midi_inst_[84] = "Lead 5 (Charang)";
    midi_inst_[85] = "Lead 6 (Voice)";
    midi_inst_[86] = "Lead 7 (Fifths)";
    midi_inst_[87] = "Lead 8 (Lead+Bass)";
    midi_inst_[88] = "Pad 1 (New age)";
    midi_inst_[89] = "Pad 2 (Warm)";
    midi_inst_[90] = "Pad 3 (Polysynth)";
    midi_inst_[91] = "Pad 4 (Choir)";
    midi_inst_[92] = "Pad 5 (Bowed)";
    midi_inst_[93] = "Pad 6 (Metallic)";
    midi_inst_[94] = "Pad 7 (Halo)";
    midi_inst_[95] = "Pad 8 (Sweep)";
    midi_inst_[96] = "FX 1 (Rain)";
    midi_inst_[97] = "FX 2 (Soundtrack)";
    midi_inst_[98] = "FX 3 (Crystal)";
    midi_inst_[99] = "FX 4 (Atmosphere)";
    midi_inst_[100] = "FX 5 (Brightness)";
    midi_inst_[101] = "FX 6 (Goblins)";
    midi_inst_[102] = "FX 7 (Echoes)";
    midi_inst_[103] = "FX 8 (Sci-fi)";
    midi_inst_[104] = "Sitar";
    midi_inst_[105] = "Banjo";
    midi_inst_[106] = "Shamisen";
    midi_inst_[107] = "Koto";
    midi_inst_[108] = "Kalimba";
    midi_inst_[109] = "Bagpipe";
    midi_inst_[110] = "Fiddle";
    midi_inst_[111] = "Shanai";
    midi_inst_[112] = "Tinkle Bell";
    midi_inst_[113] = "Agogo Bells";
    midi_inst_[114] = "Steel Drums";
    midi_inst_[115] = "Woodblock";
    midi_inst_[116] = "Taiko Drum";
    midi_inst_[117] = "Melodic Tom";
    midi_inst_[118] = "Synth Drum";
    midi_inst_[119] = "Reverse Cymbal";
    midi_inst_[120] = "Guitar Fret Noise";
    midi_inst_[121] = "Breath Noise";
    midi_inst_[122] = "Seashore";
    midi_inst_[123] = "Bird Tweet";
    midi_inst_[124] = "Telephone";
    midi_inst_[125] = "Helicopter";
    midi_inst_[126] = "Applause/Noise";
    midi_inst_[127] = "Gunshot";
}

void Midi_Db::init_midi_perc()
{
    midi_perc_[0] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 0>"};
    midi_perc_[1] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 1>"};
    midi_perc_[2] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 2>"};
    midi_perc_[3] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 3>"};
    midi_perc_[4] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 4>"};
    midi_perc_[5] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 5>"};
    midi_perc_[6] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 6>"};
    midi_perc_[7] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 7>"};
    midi_perc_[8] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 8>"};
    midi_perc_[9] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 9>"};
    midi_perc_[10] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 10>"};
    midi_perc_[11] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 11>"};
    midi_perc_[12] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 12>"};
    midi_perc_[13] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Surdo Mute"};
    midi_perc_[14] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Surdo Open"};
    midi_perc_[15] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "High Q"};
    midi_perc_[16] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Whip Slap"};
    midi_perc_[17] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Scratch Push"};
    midi_perc_[18] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Scratch Pull"};
    midi_perc_[19] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Finger Snap"};
    midi_perc_[20] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Click Noise"};
    midi_perc_[21] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Metronome Click"};
    midi_perc_[22] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Metronome Bell"};
    midi_perc_[23] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Seq Click L"};
    midi_perc_[24] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Seq Click H"};
    midi_perc_[25] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Brush Tap"};
    midi_perc_[26] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Brush Swirl L"};
    midi_perc_[27] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "High Q"};  // (XG) Brush Slap
    midi_perc_[28] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Slap"};  // (XG) Brush Swirl H
    midi_perc_[29] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Scratch Push"};  // (XG) Snare Roll
    midi_perc_[30] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Scratch Pull"};  // (XG) Castanet
    midi_perc_[31] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Sticks"};  // (XG) Snare L
    midi_perc_[32] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Square Click"};  // (XG) Sticks
    midi_perc_[33] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Metronome Click"};  // (XG) Bass Drum L
    midi_perc_[34] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Metronome Bell"};  // (XG) Open Rim Shot
    midi_perc_[35] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Acoustic Bass Drum"};
    midi_perc_[36] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Bass Drum 1"};
    midi_perc_[37] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Side Stick"};
    midi_perc_[38] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Acoustic Snare"};
    midi_perc_[39] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Hand Clap"};
    midi_perc_[40] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Electric Snare"};
    midi_perc_[41] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Low Floor Tom"};
    midi_perc_[42] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Closed High Hat"};
    midi_perc_[43] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "High Floor Tom"};
    midi_perc_[44] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Pedal High Hat"};
    midi_perc_[45] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Low Tom"};
    midi_perc_[46] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Open High Hat"};
    midi_perc_[47] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Low-Mid Tom"};
    midi_perc_[48] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "High-Mid Tom"};
    midi_perc_[49] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Crash Cymbal 1"};
    midi_perc_[50] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "High Tom"};
    midi_perc_[51] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Ride Cymbal 1"};
    midi_perc_[52] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Chinese Cymbal"};
    midi_perc_[53] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Ride Bell"};
    midi_perc_[54] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Tambourine"};
    midi_perc_[55] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Splash Cymbal"};
    midi_perc_[56] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Cow Bell"};
    midi_perc_[57] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Crash Cymbal 2"};
    midi_perc_[58] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Vibraslap"};
    midi_perc_[59] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Ride Cymbal 2"};
    midi_perc_[60] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "High Bongo"};
    midi_perc_[61] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Low Bongo"};
    midi_perc_[62] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Mute High Conga"};
    midi_perc_[63] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Open High Conga"};
    midi_perc_[64] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Low Conga"};
    midi_perc_[65] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "High Timbale"};
    midi_perc_[66] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Low Timbale"};
    midi_perc_[67] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "High Agogo"};
    midi_perc_[68] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Low Agogo"};
    midi_perc_[69] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Cabasa"};
    midi_perc_[70] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Maracas"};
    midi_perc_[71] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Short Whistle"};
    midi_perc_[72] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Long Whistle"};
    midi_perc_[73] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Short Guiro"};
    midi_perc_[74] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Long Guiro"};
    midi_perc_[75] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Claves"};
    midi_perc_[76] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "High Wood Block"};
    midi_perc_[77] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Low Wood Block"};
    midi_perc_[78] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Mute Cuica"};
    midi_perc_[79] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Open Cuica"};
    midi_perc_[80] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Mute Triangle"};
    midi_perc_[81] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "Open Triangle"};
    midi_perc_[82] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Shaker"};
    midi_perc_[83] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Jingle Bell"};
    midi_perc_[84] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Bell Tree"};
    midi_perc_[85] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Castanets"};
    midi_perc_[86] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Mute Surdu"};
    midi_perc_[87] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Open Surdu"};
    midi_perc_[88] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 88>"};
    midi_perc_[89] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 89>"};
    midi_perc_[90] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 90>"};
    midi_perc_[91] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 91>"};
    midi_perc_[92] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 92>"};
    midi_perc_[93] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 93>"};
    midi_perc_[94] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 94>"};
    midi_perc_[95] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 95>"};
    midi_perc_[96] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 96>"};
    midi_perc_[97] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 97>"};
    midi_perc_[98] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 98>"};
    midi_perc_[99] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 99>"};
    midi_perc_[100] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 100>"};
    midi_perc_[101] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 101>"};
    midi_perc_[102] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 102>"};
    midi_perc_[103] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 103>"};
    midi_perc_[104] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 104>"};
    midi_perc_[105] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 105>"};
    midi_perc_[106] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 106>"};
    midi_perc_[107] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 107>"};
    midi_perc_[108] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 108>"};
    midi_perc_[109] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 109>"};
    midi_perc_[110] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 110>"};
    midi_perc_[111] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 111>"};
    midi_perc_[112] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 112>"};
    midi_perc_[113] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 113>"};
    midi_perc_[114] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 114>"};
    midi_perc_[115] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 115>"};
    midi_perc_[116] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 116>"};
    midi_perc_[117] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 117>"};
    midi_perc_[118] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 118>"};
    midi_perc_[119] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 119>"};
    midi_perc_[120] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 120>"};
    midi_perc_[121] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 121>"};
    midi_perc_[122] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 122>"};
    midi_perc_[123] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 123>"};
    midi_perc_[124] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 124>"};
    midi_perc_[125] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 125>"};
    midi_perc_[126] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 126>"};
    midi_perc_[127] = Midi_Program_Ex{.spec = Midi_Spec::GM, .name = "<Reserved 127>"};
}

namespace {

constexpr unsigned midi_ex_id(unsigned msb, unsigned lsb, unsigned pgm) noexcept
{
    return ((msb & 0x7f) << 14) | ((lsb & 0x7f) << 7) | (pgm & 0x7f);
}

}  // namespace

void Midi_Db::init_midi_ex()
{
    midi_ex_[midi_ex_id(0x1, 00, 0x26)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Synth Bass 101"};
    midi_ex_[midi_ex_id(0x1, 00, 0x39)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Trombone 2"};
    midi_ex_[midi_ex_id(0x1, 00, 0x3c)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "French Horn2"};
    midi_ex_[midi_ex_id(0x1, 00, 0x50)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Square"};
    midi_ex_[midi_ex_id(0x1, 00, 0x51)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Saw"};
    midi_ex_[midi_ex_id(0x1, 00, 0x62)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Syn Mallet"};
    midi_ex_[midi_ex_id(0x1, 00, 0x66)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Echo Bell"};
    midi_ex_[midi_ex_id(0x1, 00, 0x68)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Sitar 2"};
    midi_ex_[midi_ex_id(0x1, 00, 0x78)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Gt. Cut Noise"};
    midi_ex_[midi_ex_id(0x1, 00, 0x79)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Flute Key Click"};
    midi_ex_[midi_ex_id(0x1, 00, 0x7a)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Rain"};
    midi_ex_[midi_ex_id(0x1, 00, 0x7b)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Dog"};
    midi_ex_[midi_ex_id(0x1, 00, 0x7c)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Telephone 2"};
    midi_ex_[midi_ex_id(0x1, 00, 0x7d)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Car-Engine"};
    midi_ex_[midi_ex_id(0x1, 00, 0x7e)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Laughing"};
    midi_ex_[midi_ex_id(0x1, 00, 0x7f)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Machine Gun"};
    midi_ex_[midi_ex_id(0x2, 00, 0x66)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Echo Pan"};
    midi_ex_[midi_ex_id(0x2, 00, 0x78)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "String Slap"};
    midi_ex_[midi_ex_id(0x2, 00, 0x7a)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Thunder"};
    midi_ex_[midi_ex_id(0x2, 00, 0x7b)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Horse-Gallop"};
    midi_ex_[midi_ex_id(0x2, 00, 0x7c)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Door Creaking"};
    midi_ex_[midi_ex_id(0x2, 00, 0x7d)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Car-Stop"};
    midi_ex_[midi_ex_id(0x2, 00, 0x7e)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Screaming"};
    midi_ex_[midi_ex_id(0x2, 00, 0x7f)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Lasergun"};
    midi_ex_[midi_ex_id(0x3, 00, 0x7a)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Wind"};
    midi_ex_[midi_ex_id(0x3, 00, 0x7b)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Bird 2"};
    midi_ex_[midi_ex_id(0x3, 00, 0x7c)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Door Close"};
    midi_ex_[midi_ex_id(0x3, 00, 0x7d)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Car-Pass"};
    midi_ex_[midi_ex_id(0x3, 00, 0x7e)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Punch"};
    midi_ex_[midi_ex_id(0x3, 00, 0x7f)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Explosion"};
    midi_ex_[midi_ex_id(0x4, 00, 0x7a)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Stream"};
    midi_ex_[midi_ex_id(0x4, 00, 0x7c)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Scratch"};
    midi_ex_[midi_ex_id(0x4, 00, 0x7d)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Car-Crash"};
    midi_ex_[midi_ex_id(0x4, 00, 0x7e)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Heart Beat"};
    midi_ex_[midi_ex_id(0x5, 00, 0x7a)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Bubble"};
    midi_ex_[midi_ex_id(0x5, 00, 0x7c)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Windchime"};
    midi_ex_[midi_ex_id(0x5, 00, 0x7d)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Siren"};
    midi_ex_[midi_ex_id(0x5, 00, 0x7e)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Footsteps"};
    midi_ex_[midi_ex_id(0x6, 00, 0x7d)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Train"};
    midi_ex_[midi_ex_id(0x7, 00, 0x7d)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Jetplane"};
    midi_ex_[midi_ex_id(0x8, 00, 00)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Piano 1w"};
    midi_ex_[midi_ex_id(0x8, 00, 0x1)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Piano 2w"};
    midi_ex_[midi_ex_id(0x8, 00, 0x2)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Piano 3w"};
    midi_ex_[midi_ex_id(0x8, 00, 0x3)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Honky-tonk w/Old Upright"};
    midi_ex_[midi_ex_id(0x8, 00, 0x4)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Detuned EP 1"};
    midi_ex_[midi_ex_id(0x8, 00, 0x5)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Detuned EP 2"};
    midi_ex_[midi_ex_id(0x8, 00, 0x6)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Coupled Hps."};
    midi_ex_[midi_ex_id(0x8, 00, 0xb)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Vib.w"};
    midi_ex_[midi_ex_id(0x8, 00, 0xc)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Marimba w"};
    midi_ex_[midi_ex_id(0x8, 00, 0xe)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Church Bell"};
    midi_ex_[midi_ex_id(0x8, 00, 0x10)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Detuned Or.1"};
    midi_ex_[midi_ex_id(0x8, 00, 0x11)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Detuned Or.2"};
    midi_ex_[midi_ex_id(0x8, 00, 0x13)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Church Org.2"};
    midi_ex_[midi_ex_id(0x8, 00, 0x15)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Accordion It"};
    midi_ex_[midi_ex_id(0x8, 00, 0x18)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Ukulele"};
    midi_ex_[midi_ex_id(0x8, 00, 0x19)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "12-str Guitar"};
    midi_ex_[midi_ex_id(0x8, 00, 0x1a)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Hawaiian Gt./Pedal Steel"};
    midi_ex_[midi_ex_id(0x8, 00, 0x1b)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Chorus Gt."};
    midi_ex_[midi_ex_id(0x8, 00, 0x1c)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Funk Gt/Funk Pop"};
    midi_ex_[midi_ex_id(0x8, 00, 0x1e)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Feedback Gt."};
    midi_ex_[midi_ex_id(0x8, 00, 0x1f)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Gt.Feedback"};
    midi_ex_[midi_ex_id(0x8, 00, 0x26)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Synth Bass 3/Acid Bass"};
    midi_ex_[midi_ex_id(0x8, 00, 0x27)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Synth Bass 4/Beef FM Bass"};
    midi_ex_[midi_ex_id(0x8, 00, 0x28)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Slow Violin"};
    midi_ex_[midi_ex_id(0x8, 00, 0x30)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Orchestra"};
    midi_ex_[midi_ex_id(0x8, 00, 0x32)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Syn.Strings 3"};
    midi_ex_[midi_ex_id(0x8, 00, 0x3d)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Brass 2"};
    midi_ex_[midi_ex_id(0x8, 00, 0x3e)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Synth Brass 3"};
    midi_ex_[midi_ex_id(0x8, 00, 0x3f)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Synth Brass 4"};
    midi_ex_[midi_ex_id(0x8, 00, 0x50)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Sine Wave"};
    midi_ex_[midi_ex_id(0x8, 00, 0x51)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Doctor Solo"};
    midi_ex_[midi_ex_id(0x8, 00, 0x6b)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Taisho Koto"};
    midi_ex_[midi_ex_id(0x8, 00, 0x73)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Castanets"};
    midi_ex_[midi_ex_id(0x8, 00, 0x74)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Concert Bass Drum"};
    midi_ex_[midi_ex_id(0x8, 00, 0x75)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Melo. Tom 2"};
    midi_ex_[midi_ex_id(0x8, 00, 0x76)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "808 Tom"};
    midi_ex_[midi_ex_id(0x8, 00, 0x7d)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Starship"};
    midi_ex_[midi_ex_id(0x9, 00, 0xe)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Carillon"};
    midi_ex_[midi_ex_id(0x9, 00, 0x76)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Elec Perc"};
    midi_ex_[midi_ex_id(0x9, 00, 0x7d)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Burst Noise"};
    midi_ex_[midi_ex_id(0x10, 00, 00)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Piano 1d"};
    midi_ex_[midi_ex_id(0x10, 00, 0x4)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "E.Piano 1w"};
    midi_ex_[midi_ex_id(0x10, 00, 0x5)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "E.Piano 2w/Soft FM EP"};
    midi_ex_[midi_ex_id(0x10, 00, 0x6)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Harpsi.w"};
    midi_ex_[midi_ex_id(0x10, 00, 0x10)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "60's Organ 1"};
    midi_ex_[midi_ex_id(0x10, 00, 0x13)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Church Org.3"};
    midi_ex_[midi_ex_id(0x10, 00, 0x18)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Nylon Gt.o"};
    midi_ex_[midi_ex_id(0x10, 00, 0x19)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Mandolin"};
    midi_ex_[midi_ex_id(0x10, 00, 0x1c)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Funk Gt.2"};
    midi_ex_[midi_ex_id(0x10, 00, 0x27)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Rubber Bass"};
    midi_ex_[midi_ex_id(0x10, 00, 0x3e)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Analog Brass1/Octave Brass"};
    midi_ex_[midi_ex_id(0x10, 00, 0x3f)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Analog Brass 2/Velo Brass 1"};
    midi_ex_[midi_ex_id(0x18, 00, 0x4)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "60's E.Piano"};
    midi_ex_[midi_ex_id(0x18, 00, 0x6)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Harpsi.o"};
    midi_ex_[midi_ex_id(0x20, 00, 0x10)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Organ 4"};
    midi_ex_[midi_ex_id(0x20, 00, 0x11)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Organ 5"};
    midi_ex_[midi_ex_id(0x20, 00, 0x18)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Nylon Gt.2"};
    midi_ex_[midi_ex_id(0x20, 00, 0x34)] = Midi_Program_Ex{.spec = Midi_Spec::GS, .name = "Choir Aahs 2"};
    midi_ex_[midi_ex_id(0x1, 00, 0x2)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "EG+Rhodes1"};
    midi_ex_[midi_ex_id(0x1, 00, 0xb)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Hard Vibe"};
    midi_ex_[midi_ex_id(0x1, 00, 0xf)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Santur 2"};
    midi_ex_[midi_ex_id(0x1, 00, 0x10)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Organ 101"};
    midi_ex_[midi_ex_id(0x1, 00, 0x11)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Organ 201"};
    midi_ex_[midi_ex_id(0x1, 00, 0x16)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Harmonica 2"};
    midi_ex_[midi_ex_id(0x1, 00, 0x1a)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Mellow Gt."};
    midi_ex_[midi_ex_id(0x1, 00, 0x1c)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Muted Dis.Gt"};
    midi_ex_[midi_ex_id(0x1, 00, 0x1e)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Dist.Gt 2"};
    midi_ex_[midi_ex_id(0x1, 00, 0x21)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Fingered Bs2"};
    midi_ex_[midi_ex_id(0x1, 00, 0x23)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Fretless Bs2"};
    midi_ex_[midi_ex_id(0x1, 00, 0x27)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Synth Bass 201"};
    midi_ex_[midi_ex_id(0x1, 00, 0x30)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Strings 2"};
    midi_ex_[midi_ex_id(0x1, 00, 0x31)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "SlowStrings2"};
    midi_ex_[midi_ex_id(0x1, 00, 0x32)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "OB Strings"};
    midi_ex_[midi_ex_id(0x1, 00, 0x38)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Trumpet 2"};
    midi_ex_[midi_ex_id(0x1, 00, 0x3a)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Tuba 2"};
    midi_ex_[midi_ex_id(0x1, 00, 0x3e)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Poly Brass"};
    midi_ex_[midi_ex_id(0x1, 00, 0x3f)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Soft Brass"};
    midi_ex_[midi_ex_id(0x1, 00, 0x52)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Vent Synth"};
    midi_ex_[midi_ex_id(0x1, 00, 0x56)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Big Fives"};
    midi_ex_[midi_ex_id(0x1, 00, 0x57)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Big & Raw"};
    midi_ex_[midi_ex_id(0x1, 00, 0x58)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Fantasia 2"};
    midi_ex_[midi_ex_id(0x1, 00, 0x59)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Thick Pad"};
    midi_ex_[midi_ex_id(0x1, 00, 0x5a)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "80's PolySyn"};
    midi_ex_[midi_ex_id(0x1, 00, 0x5b)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Heaven II"};
    midi_ex_[midi_ex_id(0x1, 00, 0x5d)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Tine Pad"};
    midi_ex_[midi_ex_id(0x1, 00, 0x5f)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Polar Pad"};
    midi_ex_[midi_ex_id(0x1, 00, 0x60)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Harmo Rain"};
    midi_ex_[midi_ex_id(0x1, 00, 0x61)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Ancestral"};
    midi_ex_[midi_ex_id(0x1, 00, 0x63)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Warm Atmos"};
    midi_ex_[midi_ex_id(0x1, 00, 0x65)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Goblinson"};
    midi_ex_[midi_ex_id(0x1, 00, 0x67)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Star Theme 2"};
    midi_ex_[midi_ex_id(0x1, 00, 0x69)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Muted Banjo"};
    midi_ex_[midi_ex_id(0x1, 00, 0x6a)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Tsugaru"};
    midi_ex_[midi_ex_id(0x1, 00, 0x6f)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Shanai 2"};
    midi_ex_[midi_ex_id(0x1, 00, 0x75)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Real Tom"};
    midi_ex_[midi_ex_id(0x1, 00, 0x77)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Reverse Cym2"};
    midi_ex_[midi_ex_id(0x2, 00, 0x2)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "EG+Rhodes2"};
    midi_ex_[midi_ex_id(0x2, 00, 0x1e)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Dazed Guitar"};
    midi_ex_[midi_ex_id(0x2, 00, 0x21)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Jazz Bass"};
    midi_ex_[midi_ex_id(0x2, 00, 0x23)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Fretless Bs3"};
    midi_ex_[midi_ex_id(0x2, 00, 0x27)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Modular Bass"};
    midi_ex_[midi_ex_id(0x2, 00, 0x50)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Hollow Mini"};
    midi_ex_[midi_ex_id(0x2, 00, 0x51)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Pulse Saw"};
    midi_ex_[midi_ex_id(0x2, 00, 0x52)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Pure PanLead"};
    midi_ex_[midi_ex_id(0x2, 00, 0x57)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Fat & Perky"};
    midi_ex_[midi_ex_id(0x2, 00, 0x59)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Horn Pad"};
    midi_ex_[midi_ex_id(0x2, 00, 0x5d)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Panner Pad"};
    midi_ex_[midi_ex_id(0x2, 00, 0x60)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "African Wood"};
    midi_ex_[midi_ex_id(0x2, 00, 0x61)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Prologue"};
    midi_ex_[midi_ex_id(0x2, 00, 0x62)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Soft Crystal"};
    midi_ex_[midi_ex_id(0x2, 00, 0x63)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Nylon Harp"};
    midi_ex_[midi_ex_id(0x2, 00, 0x65)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "50's Sci-Fi"};
    midi_ex_[midi_ex_id(0x2, 00, 0x68)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Detune Sitar"};
    midi_ex_[midi_ex_id(0x3, 00, 0x23)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Fretless Bs4"};
    midi_ex_[midi_ex_id(0x3, 00, 0x27)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Seq Bass"};
    midi_ex_[midi_ex_id(0x3, 00, 0x50)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Mellow FM"};
    midi_ex_[midi_ex_id(0x3, 00, 0x51)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Feline GR"};
    midi_ex_[midi_ex_id(0x3, 00, 0x59)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "RotaryString"};
    midi_ex_[midi_ex_id(0x3, 00, 0x62)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Round Glock"};
    midi_ex_[midi_ex_id(0x3, 00, 0x63)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Harpvox"};
    midi_ex_[midi_ex_id(0x3, 00, 0x66)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Echo Pan 2"};
    midi_ex_[midi_ex_id(0x3, 00, 0x78)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Gt.CutNoise2"};
    midi_ex_[midi_ex_id(0x4, 00, 0x50)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "CC Solo"};
    midi_ex_[midi_ex_id(0x4, 00, 0x51)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Big Lead"};
    midi_ex_[midi_ex_id(0x4, 00, 0x59)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Soft Pad"};
    midi_ex_[midi_ex_id(0x4, 00, 0x62)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Loud Glock"};
    midi_ex_[midi_ex_id(0x4, 00, 0x63)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "HollowReleas"};
    midi_ex_[midi_ex_id(0x4, 00, 0x66)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Big Panner"};
    midi_ex_[midi_ex_id(0x4, 00, 0x78)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Dist.CutNoise"};
    midi_ex_[midi_ex_id(0x4, 00, 0x7b)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Kitty"};
    midi_ex_[midi_ex_id(0x5, 00, 0x23)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Mr.Smooth"};
    midi_ex_[midi_ex_id(0x5, 00, 0x50)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Shmoog"};
    midi_ex_[midi_ex_id(0x5, 00, 0x51)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Velo Lead"};
    midi_ex_[midi_ex_id(0x5, 00, 0x62)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "GlockenChime"};
    midi_ex_[midi_ex_id(0x5, 00, 0x63)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Nylon+Rhodes"};
    midi_ex_[midi_ex_id(0x5, 00, 0x66)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Reso Panner"};
    midi_ex_[midi_ex_id(0x5, 00, 0x78)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Bass Slide"};
    midi_ex_[midi_ex_id(0x5, 00, 0x7b)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Growl"};
    midi_ex_[midi_ex_id(0x6, 00, 0x50)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "LM Square"};
    midi_ex_[midi_ex_id(0x6, 00, 0x51)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "GR-300"};
    midi_ex_[midi_ex_id(0x6, 00, 0x62)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Clear Bells"};
    midi_ex_[midi_ex_id(0x6, 00, 0x63)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Ambient Pad"};
    midi_ex_[midi_ex_id(0x6, 00, 0x66)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Water Piano"};
    midi_ex_[midi_ex_id(0x6, 00, 0x78)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Pick Scrape"};
    midi_ex_[midi_ex_id(0x6, 00, 0x7e)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Applause 2"};
    midi_ex_[midi_ex_id(0x7, 00, 0x51)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "LA Saw"};
    midi_ex_[midi_ex_id(0x7, 00, 0x62)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "ChristmasBel"};
    midi_ex_[midi_ex_id(0x7, 00, 0x7c)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Scratch 2"};
    midi_ex_[midi_ex_id(0x8, 00, 0xf)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Cimbalom"};
    midi_ex_[midi_ex_id(0x8, 00, 0x12)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Rotary Org."};
    midi_ex_[midi_ex_id(0x8, 00, 0x22)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Mute PickBs."};
    midi_ex_[midi_ex_id(0x8, 00, 0x24)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Reso Slap"};
    midi_ex_[midi_ex_id(0x8, 00, 0x2c)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Slow Tremolo"};
    midi_ex_[midi_ex_id(0x8, 00, 0x31)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Legato Str."};
    midi_ex_[midi_ex_id(0x8, 00, 0x34)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "St.Choir"};
    midi_ex_[midi_ex_id(0x8, 00, 0x36)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Syn.Voice"};
    midi_ex_[midi_ex_id(0x8, 00, 0x37)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Impact Hit"};
    midi_ex_[midi_ex_id(0x8, 00, 0x38)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Flugel Horn"};
    midi_ex_[midi_ex_id(0x8, 00, 0x3c)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Fr.Horn Solo"};
    midi_ex_[midi_ex_id(0x8, 00, 0x41)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Hyper Alto"};
    midi_ex_[midi_ex_id(0x8, 00, 0x42)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "BreathyTenor"};
    midi_ex_[midi_ex_id(0x8, 00, 0x47)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Bs.Clarinet"};
    midi_ex_[midi_ex_id(0x8, 00, 0x4b)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Kawala"};
    midi_ex_[midi_ex_id(0x8, 00, 0x54)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Dist.Lead"};
    midi_ex_[midi_ex_id(0x8, 00, 0x5f)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Converge"};
    midi_ex_[midi_ex_id(0x8, 00, 0x60)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Clavi Pad"};
    midi_ex_[midi_ex_id(0x8, 00, 0x61)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Rave"};
    midi_ex_[midi_ex_id(0x8, 00, 0x62)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Vibra Bells"};
    midi_ex_[midi_ex_id(0x8, 00, 0x68)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Tambra"};
    midi_ex_[midi_ex_id(0x8, 00, 0x69)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Rabab"};
    midi_ex_[midi_ex_id(0x8, 00, 0x6f)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Pungi"};
    midi_ex_[midi_ex_id(0x8, 00, 0x70)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Bonang"};
    midi_ex_[midi_ex_id(0x8, 00, 0x71)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Atarigane"};
    midi_ex_[midi_ex_id(0x8, 00, 0x77)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Rev.Snare 1"};
    midi_ex_[midi_ex_id(0x9, 00, 0x10)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Organ 109"};
    midi_ex_[midi_ex_id(0x9, 00, 0x19)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Nylon+Steel"};
    midi_ex_[midi_ex_id(0x9, 00, 0x1e)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Feedback Gt2"};
    midi_ex_[midi_ex_id(0x9, 00, 0x27)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "X Wire Bass"};
    midi_ex_[midi_ex_id(0x9, 00, 0x2c)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Suspense Str"};
    midi_ex_[midi_ex_id(0x9, 00, 0x30)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Orchestra 2"};
    midi_ex_[midi_ex_id(0x9, 00, 0x31)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Warm Strings"};
    midi_ex_[midi_ex_id(0x9, 00, 0x34)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Mello Choir"};
    midi_ex_[midi_ex_id(0x9, 00, 0x37)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Philly Hit"};
    midi_ex_[midi_ex_id(0x9, 00, 0x3e)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Quack Brass"};
    midi_ex_[midi_ex_id(0x9, 00, 0x5f)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Shwimmer"};
    midi_ex_[midi_ex_id(0x9, 00, 0x62)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Digi Bells"};
    midi_ex_[midi_ex_id(0x9, 00, 0x70)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Gender"};
    midi_ex_[midi_ex_id(0x9, 00, 0x75)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Rock Tom"};
    midi_ex_[midi_ex_id(0x9, 00, 0x77)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Rev.Snare 2"};
    midi_ex_[midi_ex_id(0xa, 00, 0x26)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Tekno Bass"};
    midi_ex_[midi_ex_id(0xa, 00, 0x30)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Tremolo Orch"};
    midi_ex_[midi_ex_id(0xa, 00, 0x31)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "St.Slow Str."};
    midi_ex_[midi_ex_id(0xa, 00, 0x37)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Double Hit"};
    midi_ex_[midi_ex_id(0xa, 00, 0x5f)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Celestial Pd"};
    midi_ex_[midi_ex_id(0xa, 00, 0x70)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Gamelan Gong"};
    midi_ex_[midi_ex_id(0xb, 00, 0x30)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Choir Str."};
    midi_ex_[midi_ex_id(0xb, 00, 0x70)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "St.Gamelan"};
    midi_ex_[midi_ex_id(0x10, 00, 0xc)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Barafon"};
    midi_ex_[midi_ex_id(0x10, 00, 0x12)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Rotary Org.S"};
    midi_ex_[midi_ex_id(0x10, 00, 0x1e)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Power Guitar"};
    midi_ex_[midi_ex_id(0x10, 00, 0x1f)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Ac.Gt.Harmonx"};
    midi_ex_[midi_ex_id(0x10, 00, 0x26)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Reso SH Bass"};
    midi_ex_[midi_ex_id(0x10, 00, 0x30)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "St.Strings"};
    midi_ex_[midi_ex_id(0x10, 00, 0x37)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Lo Fi Rave"};
    midi_ex_[midi_ex_id(0x10, 00, 0x3c)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Horn Orch"};
    midi_ex_[midi_ex_id(0x10, 00, 0x3d)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Brass Fall"};
    midi_ex_[midi_ex_id(0x10, 00, 0x51)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Waspy Synth"};
    midi_ex_[midi_ex_id(0x10, 00, 0x62)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Choral Bells"};
    midi_ex_[midi_ex_id(0x10, 00, 0x68)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Tamboura"};
    midi_ex_[midi_ex_id(0x10, 00, 0x69)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Gopichant"};
    midi_ex_[midi_ex_id(0x10, 00, 0x6b)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Kanoon"};
    midi_ex_[midi_ex_id(0x10, 00, 0x6f)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Hichiriki"};
    midi_ex_[midi_ex_id(0x10, 00, 0x70)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "RAMA Cymbal"};
    midi_ex_[midi_ex_id(0x10, 00, 0x77)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Rev.Kick 1"};
    midi_ex_[midi_ex_id(0x11, 00, 0xc)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Barafon 2"};
    midi_ex_[midi_ex_id(0x11, 00, 0x10)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "60's Organ 2"};
    midi_ex_[midi_ex_id(0x11, 00, 0x1e)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Power Gt.2"};
    midi_ex_[midi_ex_id(0x11, 00, 0x27)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "SH101 Bass 1"};
    midi_ex_[midi_ex_id(0x11, 00, 0x3f)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Velo Brass 2"};
    midi_ex_[midi_ex_id(0x11, 00, 0x62)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Air Bells"};
    midi_ex_[midi_ex_id(0x11, 00, 0x77)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Rev.ConBD"};
    midi_ex_[midi_ex_id(0x12, 00, 0x10)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "60's Organ 3"};
    midi_ex_[midi_ex_id(0x12, 00, 0x1e)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "5th Dist."};
    midi_ex_[midi_ex_id(0x12, 00, 0x27)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "SH101 Bass 2"};
    midi_ex_[midi_ex_id(0x12, 00, 0x62)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Bell Harp"};
    midi_ex_[midi_ex_id(0x13, 00, 0x27)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Smooth Bass"};
    midi_ex_[midi_ex_id(0x13, 00, 0x62)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Gamelimba"};
    midi_ex_[midi_ex_id(0x18, 00, 0x5)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Hard FM EP"};
    midi_ex_[midi_ex_id(0x18, 00, 0xc)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Log Drum"};
    midi_ex_[midi_ex_id(0x18, 00, 0x10)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Cheese Organ"};
    midi_ex_[midi_ex_id(0x18, 00, 0x12)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Rotary Org.F"};
    midi_ex_[midi_ex_id(0x18, 00, 0x13)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Organ Flute"};
    midi_ex_[midi_ex_id(0x18, 00, 0x18)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Velo Harmnix"};
    midi_ex_[midi_ex_id(0x18, 00, 0x1e)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Rock Rhythm"};
    midi_ex_[midi_ex_id(0x18, 00, 0x30)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Velo Strings"};
    midi_ex_[midi_ex_id(0x18, 00, 0x38)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Bright Tp."};
    midi_ex_[midi_ex_id(0x18, 00, 0x69)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Oud"};
    midi_ex_[midi_ex_id(0x18, 00, 0x77)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Rev.Tom 1"};
    midi_ex_[midi_ex_id(0x19, 00, 0x4)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Hard Rhodes"};
    midi_ex_[midi_ex_id(0x19, 00, 0x1e)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Rock Rhythm2"};
    midi_ex_[midi_ex_id(0x19, 00, 0x38)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Warm Tp."};
    midi_ex_[midi_ex_id(0x19, 00, 0x77)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Rev.Tom 2"};
    midi_ex_[midi_ex_id(0x1a, 00, 0x4)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "MellowRhodes"};
    midi_ex_[midi_ex_id(0x20, 00, 0x13)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Trem.Flute"};
    midi_ex_[midi_ex_id(0x20, 00, 0x19)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Steel Gt.2"};
    midi_ex_[midi_ex_id(0x21, 00, 0x10)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Even Bar"};
    midi_ex_[midi_ex_id(0x28, 00, 0x10)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Organ Bass"};
    midi_ex_[midi_ex_id(0x28, 00, 0x18)] = Midi_Program_Ex{.spec = Midi_Spec::SC88, .name = "Lequint Gt."};
    midi_ex_[midi_ex_id(0x7f, 00, 00)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Acou Piano 1"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x1)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Acou Piano 2"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x2)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Acou Piano 3"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x3)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Elec Piano 1"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x4)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Elec Piano 2"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x5)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Elec Piano 3"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x6)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Elec Piano 4"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x7)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Honkytonk"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x8)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Elec Org 1"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x9)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Elec Org 2"};
    midi_ex_[midi_ex_id(0x7f, 00, 0xa)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Elec Org 3"};
    midi_ex_[midi_ex_id(0x7f, 00, 0xb)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Elec Org 4"};
    midi_ex_[midi_ex_id(0x7f, 00, 0xc)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Pipe Org 1"};
    midi_ex_[midi_ex_id(0x7f, 00, 0xd)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Pipe Org 2"};
    midi_ex_[midi_ex_id(0x7f, 00, 0xe)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Pipe Org 3"};
    midi_ex_[midi_ex_id(0x7f, 00, 0xf)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Accordion"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x10)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Harpsi 1"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x11)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Harpsi 2"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x12)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Harpsi 3"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x13)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Clavi 1"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x14)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Clavi 2"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x15)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Clavi 3"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x16)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Celesta 1"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x17)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Celesta 2"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x18)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Syn Brass 1"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x19)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Syn Brass 2"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x1a)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Syn Brass 3"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x1b)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Syn Brass 4"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x1c)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Syn Bass 1"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x1d)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Syn Bass 2"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x1e)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Syn Bass 3"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x1f)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Syn Bass 4"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x20)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Fantasy"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x21)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Harmo Pan"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x22)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Chorale"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x23)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Glasses"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x24)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Soundtrack"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x25)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Atmosphere"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x26)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Warm Bell"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x27)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Funny Vox"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x28)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Echo Bell"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x29)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Ice Rain"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x2a)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Oboe 2001"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x2b)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Echo Pan"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x2c)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Doctor Solo"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x2d)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "School Daze"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x2e)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Bellsinger"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x2f)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Square Wave"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x30)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Str Sect 1"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x31)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Str Sect 2"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x32)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Str Sect 3"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x33)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Pizzicato"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x34)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Violin 1"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x35)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Violin 2"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x36)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Cello 1"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x37)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Cello 2"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x38)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Contrabass"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x39)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Harp 1"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x3a)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Harp 2"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x3b)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Guitar 1"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x3c)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Guitar 2"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x3d)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Elec Gtr 1"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x3e)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Elect Gtr 2"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x3f)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Sitar"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x40)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Acou Bass 1"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x41)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Acou Bass 2"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x42)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Elec Bass 1"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x43)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Elec Bass 2"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x44)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Slap Bass 1"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x45)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Slap Bass 2"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x46)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Fretless 1"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x47)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Fretless 2"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x48)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Flute 1"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x49)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Flute 2"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x4a)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Piccolo 1"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x4b)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Piccolo 2"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x4c)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Recorder"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x4d)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Pan Pipes"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x4e)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Sax 1"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x4f)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Sax 2"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x50)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Sax 3"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x51)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Sax 4"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x52)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Clarinet 1"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x53)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Clarinet 2"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x54)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Oboe"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x55)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Engl Horn"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x56)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Bassoon"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x57)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Harmonica"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x58)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Trumpet 1"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x59)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Trumpet 2"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x5a)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Trombone 1"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x5b)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Trombone 2"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x5c)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Fr Horn 1"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x5d)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Fr Horn 2"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x5e)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Tuba"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x5f)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Brs Sect 1"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x60)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Brs Sect 2"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x61)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Vibe 1"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x62)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Vibe 2"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x63)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Syn Mallet"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x64)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Windbell"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x65)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Glock"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x66)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Tube Bell"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x67)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Xylophone"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x68)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Marimba"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x69)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Koto"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x6a)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Sho"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x6b)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Shakuhachi"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x6c)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Whistle 1"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x6d)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Whistle 2"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x6e)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Bottleblow"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x6f)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Breathpipe"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x70)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Timpani"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x71)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Melodic Tom"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x72)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Deep Snare"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x73)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Elec Perc 1"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x74)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Elec Perc 2"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x75)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Taiko"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x76)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Taiko Rim"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x77)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Cymbal"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x78)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Castanets"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x79)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Triangle"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x7a)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Orche Hit"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x7b)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Telephone"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x7c)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Bird Tweet"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x7d)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "One Note Jam"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x7e)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Water Bell"};
    midi_ex_[midi_ex_id(0x7f, 00, 0x7f)] = Midi_Program_Ex{.spec = Midi_Spec::MT32, .name = "Jungle Tune"};
    midi_ex_[midi_ex_id(00, 0x1, 00)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Grand PianoK"};
    midi_ex_[midi_ex_id(00, 0x1, 0x1)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Bright Piano K"};
    midi_ex_[midi_ex_id(00, 0x1, 0x2)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Electric Grand Piano K"};
    midi_ex_[midi_ex_id(00, 0x1, 0x3)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Honky Tonk K"};
    midi_ex_[midi_ex_id(00, 0x1, 0x4)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Electric Piano 1K"};
    midi_ex_[midi_ex_id(00, 0x1, 0x5)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Electric Piano2 K"};
    midi_ex_[midi_ex_id(00, 0x1, 0x6)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Harpsichord K"};
    midi_ex_[midi_ex_id(00, 0x1, 0x7)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Clavinet K"};
    midi_ex_[midi_ex_id(00, 0x1, 0xb)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "VibesK"};
    midi_ex_[midi_ex_id(00, 0x1, 0xc)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Marimba K"};
    midi_ex_[midi_ex_id(00, 0x3, 0x30)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "S.Strngs"};
    midi_ex_[midi_ex_id(00, 0x3, 0x31)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "S.SlwStr"};
    midi_ex_[midi_ex_id(00, 0x3, 0x34)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "S.Choir"};
    midi_ex_[midi_ex_id(00, 0x6, 0x27)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "MelloSB1"};
    midi_ex_[midi_ex_id(00, 0x6, 0x3c)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "FrHrSolo"};
    midi_ex_[midi_ex_id(00, 0x6, 0x50)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Square 2"};
    midi_ex_[midi_ex_id(00, 0x6, 0x51)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Saw 2"};
    midi_ex_[midi_ex_id(00, 0x8, 0x28)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "SlowVln"};
    midi_ex_[midi_ex_id(00, 0x8, 0x2c)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "SlowTrStr"};
    midi_ex_[midi_ex_id(00, 0x8, 0x30)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "SlowStr"};
    midi_ex_[midi_ex_id(00, 0x8, 0x31)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "LegatoSt"};
    midi_ex_[midi_ex_id(00, 0x8, 0x50)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "LMSquare"};
    midi_ex_[midi_ex_id(00, 0x8, 0x51)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "ThickSaw"};
    midi_ex_[midi_ex_id(00, 0x8, 0x66)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "EchoPad2"};
    midi_ex_[midi_ex_id(00, 0xc, 0x27)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Seq Bass"};
    midi_ex_[midi_ex_id(00, 0xc, 0x3e)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "QuackBr"};
    midi_ex_[midi_ex_id(00, 0xc, 0x62)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "SynDrCmp"};
    midi_ex_[midi_ex_id(00, 0xe, 0x62)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Popcorn"};
    midi_ex_[midi_ex_id(00, 0xe, 0x66)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Echo Pan"};
    midi_ex_[midi_ex_id(00, 0x10, 0x18)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "NylonGt2"};
    midi_ex_[midi_ex_id(00, 0x10, 0x19)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "SteelGt2"};
    midi_ex_[midi_ex_id(00, 0x10, 0x34)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Ch.Aahs2"};
    midi_ex_[midi_ex_id(00, 0x10, 0x38)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Trumpet2"};
    midi_ex_[midi_ex_id(00, 0x10, 0x3a)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Tuba 2"};
    midi_ex_[midi_ex_id(00, 0x10, 0x57)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Big&Low"};
    midi_ex_[midi_ex_id(00, 0x10, 0x59)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "ThickPad"};
    midi_ex_[midi_ex_id(00, 0x11, 0x38)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "BriteTrp"};
    midi_ex_[midi_ex_id(00, 0x11, 0x59)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Soft Pad"};
    midi_ex_[midi_ex_id(00, 0x12, 00)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "MelloGrP"};
    midi_ex_[midi_ex_id(00, 0x12, 0x4)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "MelloEP1"};
    midi_ex_[midi_ex_id(00, 0x12, 0x1a)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "MelloGtr"};
    midi_ex_[midi_ex_id(00, 0x12, 0x21)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "FingrDrk"};
    midi_ex_[midi_ex_id(00, 0x12, 0x26)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "SynBa1Dk"};
    midi_ex_[midi_ex_id(00, 0x12, 0x27)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "SynBa1Dk"};
    midi_ex_[midi_ex_id(00, 0x12, 0x28)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "ClkSynBa"};
    midi_ex_[midi_ex_id(00, 0x12, 0x39)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Trmbone2"};
    midi_ex_[midi_ex_id(00, 0x12, 0x3f)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Soft Brs"};
    midi_ex_[midi_ex_id(00, 0x12, 0x50)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Hollow"};
    midi_ex_[midi_ex_id(00, 0x12, 0x51)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "DynaSaw"};
    midi_ex_[midi_ex_id(00, 0x12, 0x59)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "SinePad"};
    midi_ex_[midi_ex_id(00, 0x12, 0x62)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "TinyBell"};
    midi_ex_[midi_ex_id(00, 0x12, 0x63)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "WarmAtms"};
    midi_ex_[midi_ex_id(00, 0x13, 0x27)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "SynBa2Dk"};
    midi_ex_[midi_ex_id(00, 0x13, 0x50)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Shmoog"};
    midi_ex_[midi_ex_id(00, 0x13, 0x51)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "DigiSaw"};
    midi_ex_[midi_ex_id(00, 0x13, 0x63)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "HollwRls"};
    midi_ex_[midi_ex_id(00, 0x14, 0x26)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "FastResB"};
    midi_ex_[midi_ex_id(00, 0x14, 0x3e)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "RezSynBr"};
    midi_ex_[midi_ex_id(00, 0x14, 0x51)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Big Lead"};
    midi_ex_[midi_ex_id(00, 0x14, 0x5f)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Shwimmer"};
    midi_ex_[midi_ex_id(00, 0x18, 0x11)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "70sPcOr1"};
    midi_ex_[midi_ex_id(00, 0x18, 0x26)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "AcidBass"};
    midi_ex_[midi_ex_id(00, 0x18, 0x30)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "ArcoStr"};
    midi_ex_[midi_ex_id(00, 0x18, 0x3e)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "PolyBrss"};
    midi_ex_[midi_ex_id(00, 0x18, 0x51)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "HeavySyn"};
    midi_ex_[midi_ex_id(00, 0x18, 0x55)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "SynthAah"};
    midi_ex_[midi_ex_id(00, 0x19, 0x6)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Harpsi.2"};
    midi_ex_[midi_ex_id(00, 0x19, 0x18)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "NylonGt3"};
    midi_ex_[midi_ex_id(00, 0x19, 0x51)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "WaspySyn"};
    midi_ex_[midi_ex_id(00, 0x1b, 0x7)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "ClaviWah"};
    midi_ex_[midi_ex_id(00, 0x1b, 0x21)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "FlangeBa"};
    midi_ex_[midi_ex_id(00, 0x1b, 0x24)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "ResoSlap"};
    midi_ex_[midi_ex_id(00, 0x1b, 0x32)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "ResoStr"};
    midi_ex_[midi_ex_id(00, 0x1b, 0x3e)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "SynBras3"};
    midi_ex_[midi_ex_id(00, 0x1b, 0x5f)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Converge"};
    midi_ex_[midi_ex_id(00, 0x1b, 0x61)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Prologue"};
    midi_ex_[midi_ex_id(00, 0x1c, 0x22)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "MutePkBa"};
    midi_ex_[midi_ex_id(00, 0x1c, 0x69)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "MuteBnjo"};
    midi_ex_[midi_ex_id(00, 0x20, 0x2)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Det.CP80"};
    midi_ex_[midi_ex_id(00, 0x20, 0x4)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Chor.EP1"};
    midi_ex_[midi_ex_id(00, 0x20, 0x5)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Chor.EP2"};
    midi_ex_[midi_ex_id(00, 0x20, 0x10)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "DetDrwOr"};
    midi_ex_[midi_ex_id(00, 0x20, 0x11)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "DetPrcOr"};
    midi_ex_[midi_ex_id(00, 0x20, 0x13)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "ChurOrg3"};
    midi_ex_[midi_ex_id(00, 0x20, 0x15)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "AccordIt"};
    midi_ex_[midi_ex_id(00, 0x20, 0x16)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Harmo 2"};
    midi_ex_[midi_ex_id(00, 0x20, 0x1a)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "JazzAmp"};
    midi_ex_[midi_ex_id(00, 0x20, 0x1b)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "ChorusGt"};
    midi_ex_[midi_ex_id(00, 0x20, 0x23)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Fretles2"};
    midi_ex_[midi_ex_id(00, 0x20, 0x24)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "PunchThm"};
    midi_ex_[midi_ex_id(00, 0x20, 0x27)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "SmthBa 2"};
    midi_ex_[midi_ex_id(00, 0x20, 0x34)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "MelChoir"};
    midi_ex_[midi_ex_id(00, 0x20, 0x38)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "WarmTrp"};
    midi_ex_[midi_ex_id(00, 0x20, 0x3c)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "FrHorn2"};
    midi_ex_[midi_ex_id(00, 0x20, 0x3e)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "JumpBrss"};
    midi_ex_[midi_ex_id(00, 0x20, 0x68)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "DetSitar"};
    midi_ex_[midi_ex_id(00, 0x21, 0x5)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "DX Hard"};
    midi_ex_[midi_ex_id(00, 0x21, 0x10)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "60sDrOr1"};
    midi_ex_[midi_ex_id(00, 0x21, 0x11)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "LiteOrg"};
    midi_ex_[midi_ex_id(00, 0x21, 0x23)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Fretles3"};
    midi_ex_[midi_ex_id(00, 0x22, 0x5)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "DXLegend"};
    midi_ex_[midi_ex_id(00, 0x22, 0x10)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "60sDrOr2"};
    midi_ex_[midi_ex_id(00, 0x22, 0x23)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Fretles4"};
    midi_ex_[midi_ex_id(00, 0x23, 0x6)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Harpsi.3"};
    midi_ex_[midi_ex_id(00, 0x23, 0xf)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Dulcimr2"};
    midi_ex_[midi_ex_id(00, 0x23, 0x10)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "70sDrOr1"};
    midi_ex_[midi_ex_id(00, 0x23, 0x13)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "ChurOrg2"};
    midi_ex_[midi_ex_id(00, 0x23, 0x19)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "12StrGtr"};
    midi_ex_[midi_ex_id(00, 0x23, 0x26)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Clv Bass"};
    midi_ex_[midi_ex_id(00, 0x23, 0x30)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "60sStrng"};
    midi_ex_[midi_ex_id(00, 0x23, 0x37)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "OrchHit2"};
    midi_ex_[midi_ex_id(00, 0x23, 0x3d)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Tp&TbSec"};
    midi_ex_[midi_ex_id(00, 0x23, 0x56)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Big Five"};
    midi_ex_[midi_ex_id(00, 0x23, 0x62)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "RndGlock"};
    midi_ex_[midi_ex_id(00, 0x23, 0x68)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Sitar 2"};
    midi_ex_[midi_ex_id(00, 0x24, 0x10)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "DrawOrg2"};
    midi_ex_[midi_ex_id(00, 0x25, 0x10)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "60sDrOr3"};
    midi_ex_[midi_ex_id(00, 0x25, 0x11)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "PercOrg2"};
    midi_ex_[midi_ex_id(00, 0x25, 0x3c)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "HornOrch"};
    midi_ex_[midi_ex_id(00, 0x26, 0x10)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "EvenBar"};
    midi_ex_[midi_ex_id(00, 0x28, 00)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "PianoStr"};
    midi_ex_[midi_ex_id(00, 0x28, 0x2)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "ElGrPno1"};
    midi_ex_[midi_ex_id(00, 0x28, 0x4)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "HardEl.P"};
    midi_ex_[midi_ex_id(00, 0x28, 0x5)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "DX Phase"};
    midi_ex_[midi_ex_id(00, 0x28, 0x10)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "16+2\"2/3"};
    midi_ex_[midi_ex_id(00, 0x28, 0x13)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "NotreDam"};
    midi_ex_[midi_ex_id(00, 0x28, 0x14)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Puff Org"};
    midi_ex_[midi_ex_id(00, 0x28, 0x19)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Nyln&Stl"};
    midi_ex_[midi_ex_id(00, 0x28, 0x1c)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "FunkGtr1"};
    midi_ex_[midi_ex_id(00, 0x28, 0x1e)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "FeedbkGt"};
    midi_ex_[midi_ex_id(00, 0x28, 0x20)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Jazz Rhythm"};
    midi_ex_[midi_ex_id(00, 0x28, 0x21)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Ba&DstEG"};
    midi_ex_[midi_ex_id(00, 0x28, 0x26)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Techno Bass"};
    midi_ex_[midi_ex_id(00, 0x28, 0x27)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Modular Bass"};
    midi_ex_[midi_ex_id(00, 0x28, 0x2c)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Susp Str"};
    midi_ex_[midi_ex_id(00, 0x28, 0x2e)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Yang Chin"};
    midi_ex_[midi_ex_id(00, 0x28, 0x30)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Orchestra"};
    midi_ex_[midi_ex_id(00, 0x28, 0x31)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Warm Str"};
    midi_ex_[midi_ex_id(00, 0x28, 0x34)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "ChoirStr"};
    midi_ex_[midi_ex_id(00, 0x28, 0x36)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "SynVox2"};
    midi_ex_[midi_ex_id(00, 0x28, 0x3d)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "BrassSec2"};
    midi_ex_[midi_ex_id(00, 0x28, 0x3f)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "SynBras4"};
    midi_ex_[midi_ex_id(00, 0x28, 0x41)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Sax Sect"};
    midi_ex_[midi_ex_id(00, 0x28, 0x42)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "BrthTnSx"};
    midi_ex_[midi_ex_id(00, 0x28, 0x51)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Pulse Saw"};
    midi_ex_[midi_ex_id(00, 0x28, 0x62)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "GlockChi"};
    midi_ex_[midi_ex_id(00, 0x28, 0x63)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "NylonEP"};
    midi_ex_[midi_ex_id(00, 0x29, 00)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Dream"};
    midi_ex_[midi_ex_id(00, 0x29, 0x2)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "ElGrPno2"};
    midi_ex_[midi_ex_id(00, 0x29, 0x5)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "DX+Analg"};
    midi_ex_[midi_ex_id(00, 0x29, 0x19)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Stl&Body"};
    midi_ex_[midi_ex_id(00, 0x29, 0x1c)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "MuteStlG"};
    midi_ex_[midi_ex_id(00, 0x29, 0x1e)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "FeedbGt2"};
    midi_ex_[midi_ex_id(00, 0x29, 0x27)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "DX Bass"};
    midi_ex_[midi_ex_id(00, 0x29, 0x30)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Orchstr2"};
    midi_ex_[midi_ex_id(00, 0x29, 0x31)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Kingdom"};
    midi_ex_[midi_ex_id(00, 0x29, 0x36)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Choral"};
    midi_ex_[midi_ex_id(00, 0x29, 0x3d)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "HiBrass"};
    midi_ex_[midi_ex_id(00, 0x29, 0x3f)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "ChorBrss"};
    midi_ex_[midi_ex_id(00, 0x29, 0x42)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "SoftTenr"};
    midi_ex_[midi_ex_id(00, 0x29, 0x51)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Dr. Lead"};
    midi_ex_[midi_ex_id(00, 0x29, 0x62)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "ClearBel"};
    midi_ex_[midi_ex_id(00, 0x2a, 0x5)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "DXKotoEP"};
    midi_ex_[midi_ex_id(00, 0x2a, 0x30)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "TremOrch"};
    midi_ex_[midi_ex_id(00, 0x2a, 0x3d)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "MelloBrs"};
    midi_ex_[midi_ex_id(00, 0x2a, 0x62)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "ChorBell"};
    midi_ex_[midi_ex_id(00, 0x2b, 0x18)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "VelGtHrm"};
    midi_ex_[midi_ex_id(00, 0x2b, 0x1c)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "FunkGtr2"};
    midi_ex_[midi_ex_id(00, 0x2b, 0x1d)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Gt.Pinch"};
    midi_ex_[midi_ex_id(00, 0x2b, 0x21)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "FngrSlap"};
    midi_ex_[midi_ex_id(00, 0x2b, 0x25)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "VeloSlap"};
    midi_ex_[midi_ex_id(00, 0x2b, 0x41)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "HyprAlto"};
    midi_ex_[midi_ex_id(00, 0x2d, 0x4)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "VX El.P1"};
    midi_ex_[midi_ex_id(00, 0x2d, 0x5)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "VX El.P2"};
    midi_ex_[midi_ex_id(00, 0x2d, 0xb)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "HardVibe"};
    midi_ex_[midi_ex_id(00, 0x2d, 0x1c)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Jazz Man"};
    midi_ex_[midi_ex_id(00, 0x2d, 0x20)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "VX Upright"};
    midi_ex_[midi_ex_id(00, 0x2d, 0x21)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "FngBass2"};
    midi_ex_[midi_ex_id(00, 0x2d, 0x30)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "VeloStr"};
    midi_ex_[midi_ex_id(00, 0x2d, 0x3e)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "AnaVelBr"};
    midi_ex_[midi_ex_id(00, 0x2d, 0x3f)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "VelBras2"};
    midi_ex_[midi_ex_id(00, 0x2d, 0x51)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "VeloLead"};
    midi_ex_[midi_ex_id(00, 0x2d, 0x60)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "ClaviPad"};
    midi_ex_[midi_ex_id(00, 0x40, 0x4)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "60sEl.P"};
    midi_ex_[midi_ex_id(00, 0x40, 0x7)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "PulseClv"};
    midi_ex_[midi_ex_id(00, 0x40, 0xa)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Orgel"};
    midi_ex_[midi_ex_id(00, 0x40, 0xc)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "SineMrmb"};
    midi_ex_[midi_ex_id(00, 0x40, 0x10)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Organ Ba"};
    midi_ex_[midi_ex_id(00, 0x40, 0x12)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "RotaryOr"};
    midi_ex_[midi_ex_id(00, 0x40, 0x13)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "OrgFlute"};
    midi_ex_[midi_ex_id(00, 0x40, 0x17)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "TngoAcd2"};
    midi_ex_[midi_ex_id(00, 0x40, 0x26)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Oscar"};
    midi_ex_[midi_ex_id(00, 0x40, 0x27)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "X WireBa"};
    midi_ex_[midi_ex_id(00, 0x40, 0x31)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "70s Str"};
    midi_ex_[midi_ex_id(00, 0x40, 0x32)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Syn Str4"};
    midi_ex_[midi_ex_id(00, 0x40, 0x36)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "AnaVoice"};
    midi_ex_[midi_ex_id(00, 0x40, 0x37)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Impact"};
    midi_ex_[midi_ex_id(00, 0x40, 0x3e)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "AnaBrss1"};
    midi_ex_[midi_ex_id(00, 0x40, 0x3f)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "AnaBras2"};
    midi_ex_[midi_ex_id(00, 0x40, 0x42)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "TnrSax 2"};
    midi_ex_[midi_ex_id(00, 0x40, 0x50)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Mellow"};
    midi_ex_[midi_ex_id(00, 0x40, 0x53)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Rubby"};
    midi_ex_[midi_ex_id(00, 0x40, 0x54)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "DistLead"};
    midi_ex_[midi_ex_id(00, 0x40, 0x55)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "VoxLead"};
    midi_ex_[midi_ex_id(00, 0x40, 0x57)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Fat&Prky"};
    midi_ex_[midi_ex_id(00, 0x40, 0x58)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Fantasy2"};
    midi_ex_[midi_ex_id(00, 0x40, 0x59)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Horn Pad"};
    midi_ex_[midi_ex_id(00, 0x40, 0x5a)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "PolyPd80"};
    midi_ex_[midi_ex_id(00, 0x40, 0x5b)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Heaven2"};
    midi_ex_[midi_ex_id(00, 0x40, 0x5c)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Glacier"};
    midi_ex_[midi_ex_id(00, 0x40, 0x5d)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Tine Pad"};
    midi_ex_[midi_ex_id(00, 0x40, 0x5f)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "PolarPad"};
    midi_ex_[midi_ex_id(00, 0x40, 0x60)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "HrmoRain"};
    midi_ex_[midi_ex_id(00, 0x40, 0x61)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Ancestrl"};
    midi_ex_[midi_ex_id(00, 0x40, 0x62)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "SynMalet"};
    midi_ex_[midi_ex_id(00, 0x40, 0x63)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "NylnHarp"};
    midi_ex_[midi_ex_id(00, 0x40, 0x64)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "FantaBel"};
    midi_ex_[midi_ex_id(00, 0x40, 0x65)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "GobSyn"};
    midi_ex_[midi_ex_id(00, 0x40, 0x66)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "EchoBell"};
    midi_ex_[midi_ex_id(00, 0x40, 0x67)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Starz"};
    midi_ex_[midi_ex_id(00, 0x40, 0x6f)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Shanai2"};
    midi_ex_[midi_ex_id(00, 0x40, 0x75)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Mel Tom2"};
    midi_ex_[midi_ex_id(00, 0x40, 0x76)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Ana Tom"};
    midi_ex_[midi_ex_id(00, 0x41, 0x7)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "PierceCl"};
    midi_ex_[midi_ex_id(00, 0x41, 0x10)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "70sDrOr2"};
    midi_ex_[midi_ex_id(00, 0x41, 0x12)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "SlwRotar"};
    midi_ex_[midi_ex_id(00, 0x41, 0x13)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "TrmOrgFl"};
    midi_ex_[midi_ex_id(00, 0x41, 0x1f)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "GtFeedbk"};
    midi_ex_[midi_ex_id(00, 0x41, 0x21)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "ModAlem"};
    midi_ex_[midi_ex_id(00, 0x41, 0x26)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "SqrBass"};
    midi_ex_[midi_ex_id(00, 0x41, 0x32)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "SS Str"};
    midi_ex_[midi_ex_id(00, 0x41, 0x50)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "SoloSine"};
    midi_ex_[midi_ex_id(00, 0x41, 0x52)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Pure Pad"};
    midi_ex_[midi_ex_id(00, 0x41, 0x54)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "WireLead"};
    midi_ex_[midi_ex_id(00, 0x41, 0x57)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "SoftWurl"};
    midi_ex_[midi_ex_id(00, 0x41, 0x59)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "RotarStr"};
    midi_ex_[midi_ex_id(00, 0x41, 0x5a)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "ClickPad"};
    midi_ex_[midi_ex_id(00, 0x41, 0x5c)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "GlassPad"};
    midi_ex_[midi_ex_id(00, 0x41, 0x5d)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Pan Pad"};
    midi_ex_[midi_ex_id(00, 0x41, 0x60)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "AfrcnWod"};
    midi_ex_[midi_ex_id(00, 0x41, 0x62)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "SftCryst"};
    midi_ex_[midi_ex_id(00, 0x41, 0x63)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Harp Vox"};
    midi_ex_[midi_ex_id(00, 0x41, 0x65)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "50sSciFi"};
    midi_ex_[midi_ex_id(00, 0x41, 0x66)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Big Pan"};
    midi_ex_[midi_ex_id(00, 0x41, 0x75)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Real Tom"};
    midi_ex_[midi_ex_id(00, 0x41, 0x76)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "ElecPerc"};
    midi_ex_[midi_ex_id(00, 0x42, 0x10)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "CheezOrg"};
    midi_ex_[midi_ex_id(00, 0x42, 0x12)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "FstRotar"};
    midi_ex_[midi_ex_id(00, 0x42, 0x1f)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "GtrHrmo2"};
    midi_ex_[midi_ex_id(00, 0x42, 0x26)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "RubberBa"};
    midi_ex_[midi_ex_id(00, 0x42, 0x50)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "SineLead"};
    midi_ex_[midi_ex_id(00, 0x42, 0x5a)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Ana Pad"};
    midi_ex_[midi_ex_id(00, 0x42, 0x5b)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Itopia"};
    midi_ex_[midi_ex_id(00, 0x42, 0x5f)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Celstial"};
    midi_ex_[midi_ex_id(00, 0x42, 0x60)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Caribean"};
    midi_ex_[midi_ex_id(00, 0x42, 0x62)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "LoudGlok"};
    midi_ex_[midi_ex_id(00, 0x42, 0x63)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "AtmosPad"};
    midi_ex_[midi_ex_id(00, 0x42, 0x65)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Ring Pad"};
    midi_ex_[midi_ex_id(00, 0x42, 0x66)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "SynPiano"};
    midi_ex_[midi_ex_id(00, 0x42, 0x75)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Rock Tom"};
    midi_ex_[midi_ex_id(00, 0x43, 0x10)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "DrawOrg3"};
    midi_ex_[midi_ex_id(00, 0x43, 0x5a)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "SquarPad"};
    midi_ex_[midi_ex_id(00, 0x43, 0x5b)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "CC Pad"};
    midi_ex_[midi_ex_id(00, 0x43, 0x62)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "XmasBell"};
    midi_ex_[midi_ex_id(00, 0x43, 0x63)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Planet"};
    midi_ex_[midi_ex_id(00, 0x43, 0x65)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Ritual"};
    midi_ex_[midi_ex_id(00, 0x43, 0x66)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Creation"};
    midi_ex_[midi_ex_id(00, 0x44, 0x62)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "VibeBell"};
    midi_ex_[midi_ex_id(00, 0x44, 0x65)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "ToHeaven"};
    midi_ex_[midi_ex_id(00, 0x44, 0x66)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Stardust"};
    midi_ex_[midi_ex_id(00, 0x45, 0x62)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "DigiBell"};
    midi_ex_[midi_ex_id(00, 0x45, 0x66)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Reso Pan"};
    midi_ex_[midi_ex_id(00, 0x46, 0x62)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "AirBells"};
    midi_ex_[midi_ex_id(00, 0x46, 0x65)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Night"};
    midi_ex_[midi_ex_id(00, 0x47, 0x62)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "BellHarp"};
    midi_ex_[midi_ex_id(00, 0x47, 0x65)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Glisten"};
    midi_ex_[midi_ex_id(00, 0x48, 0x62)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Gamelmba"};
    midi_ex_[midi_ex_id(00, 0x60, 0xe)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Church Bell"};
    midi_ex_[midi_ex_id(00, 0x60, 0xf)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Cimbalom"};
    midi_ex_[midi_ex_id(00, 0x60, 0x18)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Ukelele"};
    midi_ex_[midi_ex_id(00, 0x60, 0x19)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Mandolin"};
    midi_ex_[midi_ex_id(00, 0x60, 0x23)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "SynFretl"};
    midi_ex_[midi_ex_id(00, 0x60, 0x26)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Hammer"};
    midi_ex_[midi_ex_id(00, 0x60, 0x51)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Seq Ana"};
    midi_ex_[midi_ex_id(00, 0x60, 0x64)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Smokey"};
    midi_ex_[midi_ex_id(00, 0x60, 0x65)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "BelChoir"};
    midi_ex_[midi_ex_id(00, 0x60, 0x68)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Tambra"};
    midi_ex_[midi_ex_id(00, 0x60, 0x69)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Rabab"};
    midi_ex_[midi_ex_id(00, 0x60, 0x6b)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "T.Koto"};
    midi_ex_[midi_ex_id(00, 0x60, 0x6f)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Pungi"};
    midi_ex_[midi_ex_id(00, 0x60, 0x70)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Bonang"};
    midi_ex_[midi_ex_id(00, 0x60, 0x73)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Castanets"};
    midi_ex_[midi_ex_id(00, 0x60, 0x74)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Gr.Cassa"};
    midi_ex_[midi_ex_id(00, 0x61, 0xc)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Balafon2"};
    midi_ex_[midi_ex_id(00, 0x61, 0xe)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Carillon"};
    midi_ex_[midi_ex_id(00, 0x61, 0xf)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Santur"};
    midi_ex_[midi_ex_id(00, 0x61, 0x23)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Smooth"};
    midi_ex_[midi_ex_id(00, 0x61, 0x68)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Tamboura"};
    midi_ex_[midi_ex_id(00, 0x61, 0x69)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Gopichnt"};
    midi_ex_[midi_ex_id(00, 0x61, 0x6b)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Kanoon"};
    midi_ex_[midi_ex_id(00, 0x61, 0x6f)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Hichriki"};
    midi_ex_[midi_ex_id(00, 0x61, 0x70)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Gender"};
    midi_ex_[midi_ex_id(00, 0x61, 0x72)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "GlasPerc"};
    midi_ex_[midi_ex_id(00, 0x62, 0xc)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Log Drum"};
    midi_ex_[midi_ex_id(00, 0x62, 0x69)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Oud"};
    midi_ex_[midi_ex_id(00, 0x62, 0x70)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Gamelan"};
    midi_ex_[midi_ex_id(00, 0x62, 0x72)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "ThaiBell"};
    midi_ex_[midi_ex_id(00, 0x63, 0x70)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "S.Gamlan"};
    midi_ex_[midi_ex_id(00, 0x64, 0x70)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "Rama Cym"};
    midi_ex_[midi_ex_id(00, 0x65, 0x70)] = Midi_Program_Ex{.spec = Midi_Spec::XG, .name = "AsianBel"};
}

const Midi_Program_Ex *Midi_Db::find_ex(unsigned msb, unsigned lsb, unsigned pgm) const
{
    // midi_ex_id() drops the percussion bit, which would give a percussion
    // key the name of the melodic program with the same number.
    if (pgm > 127)
        return nullptr;
    const auto it = midi_ex_.find(midi_ex_id(msb, lsb, pgm));
    return (it != midi_ex_.end()) ? &it->second : nullptr;
}
