/*     Part of ADLplug, distributed under the GNU GPL v3 or later.
 *               (See accompanying file LICENSE.)
 *
 * Binary resources, embedded at compile time from the files under resources/
 * with C23 #embed. resources.h makes them available to C++ as Res::<name>.
 *
 * #embed is a preprocessing directive, so it cannot be generated by a macro;
 * each resource is spelled out. Only the resources of the chip variant being
 * built are embedded, with the icons of every emulator core its library has:
 * which cores are built is a build option (cmake/ADLMIDI.cmake).
 */

#include "resources.h"

#if defined(ADLPLUG_OPL3)

static const unsigned char opl3_banks_pak[] = {
#embed "../resources/opl3/banks.pak"
};
const struct Res_Data adlplug_res_opl3_banks_pak = { opl3_banks_pak, sizeof opl3_banks_pak };

static const unsigned char emu_dosbox[] = {
#embed "../resources/ui/cores/DOSBox.png"
};
const struct Res_Data adlplug_res_emu_dosbox = { emu_dosbox, sizeof emu_dosbox };

static const unsigned char emu_nuked[] = {
#embed "../resources/ui/cores/Nuked.png"
};
const struct Res_Data adlplug_res_emu_nuked = { emu_nuked, sizeof emu_nuked };

static const unsigned char emu_nuked2[] = {
#embed "../resources/ui/cores/Nuked2.png"
};
const struct Res_Data adlplug_res_emu_nuked2 = { emu_nuked2, sizeof emu_nuked2 };

static const unsigned char emu_opal[] = {
#embed "../resources/ui/cores/Rad.png"
};
const struct Res_Data adlplug_res_emu_opal = { emu_opal, sizeof emu_opal };

static const unsigned char emu_java[] = {
#embed "../resources/ui/cores/Cafe.png"
};
const struct Res_Data adlplug_res_emu_java = { emu_java, sizeof emu_java };

static const unsigned char emu_esfmu[] = {
#embed "../resources/ui/cores/ESFMu.png"
};
const struct Res_Data adlplug_res_emu_esfmu = { emu_esfmu, sizeof emu_esfmu };

static const unsigned char emu_mame[] = {
#embed "../resources/ui/cores/MAME.png"
};
const struct Res_Data adlplug_res_emu_mame = { emu_mame, sizeof emu_mame };

static const unsigned char emoji_u1f4a1[] = {
#embed "../resources/ui/noto-emoji/emoji_u1f4a1.png"
};
const struct Res_Data adlplug_res_emoji_u1f4a1 = { emoji_u1f4a1, sizeof emoji_u1f4a1 };

#elif defined(ADLPLUG_OPN2)

static const unsigned char opn2_banks_pak[] = {
#embed "../resources/opn2/banks.pak"
};
const struct Res_Data adlplug_res_opn2_banks_pak = { opn2_banks_pak, sizeof opn2_banks_pak };

static const unsigned char emu_mame[] = {
#embed "../resources/ui/cores/MAME.png"
};
const struct Res_Data adlplug_res_emu_mame = { emu_mame, sizeof emu_mame };

static const unsigned char emu_nuked[] = {
#embed "../resources/ui/cores/Nuked.png"
};
const struct Res_Data adlplug_res_emu_nuked = { emu_nuked, sizeof emu_nuked };

static const unsigned char emu_gens[] = {
#embed "../resources/ui/cores/Gens.png"
};
const struct Res_Data adlplug_res_emu_gens = { emu_gens, sizeof emu_gens };

static const unsigned char emu_neko[] = {
#embed "../resources/ui/cores/Neko.png"
};
const struct Res_Data adlplug_res_emu_neko = { emu_neko, sizeof emu_neko };

#endif

static const unsigned char emoji_u1f4be[] = {
#embed "../resources/ui/noto-emoji/emoji_u1f4be.png"
};
const struct Res_Data adlplug_res_emoji_u1f4be = { emoji_u1f4be, sizeof emoji_u1f4be };

static const unsigned char emoji_u1f4c2[] = {
#embed "../resources/ui/noto-emoji/emoji_u1f4c2.png"
};
const struct Res_Data adlplug_res_emoji_u1f4c2 = { emoji_u1f4c2, sizeof emoji_u1f4c2 };

static const unsigned char emoji_u1f4dd[] = {
#embed "../resources/ui/noto-emoji/emoji_u1f4dd.png"
};
const struct Res_Data adlplug_res_emoji_u1f4dd = { emoji_u1f4dd, sizeof emoji_u1f4dd };

static const unsigned char emoji_u2328[] = {
#embed "../resources/ui/noto-emoji/emoji_u2328.png"
};
const struct Res_Data adlplug_res_emoji_u2328 = { emoji_u2328, sizeof emoji_u2328 };

static const unsigned char emoji_u2795[] = {
#embed "../resources/ui/noto-emoji/emoji_u2795.png"
};
const struct Res_Data adlplug_res_emoji_u2795 = { emoji_u2795, sizeof emoji_u2795 };

static const unsigned char knob_skin[] = {
#embed "../resources/ui/knob-skin.png"
};
const struct Res_Data adlplug_res_knob_skin = { knob_skin, sizeof knob_skin };

static const unsigned char slider_skin[] = {
#embed "../resources/ui/slider-skin.png"
};
const struct Res_Data adlplug_res_slider_skin = { slider_skin, sizeof slider_skin };

static const unsigned char mono_bold_italic[] = {
#embed "../resources/ui/fonts/Mono-BoldItalic.ttf.gz"
};
const struct Res_Data adlplug_res_Mono_BoldItalic = { mono_bold_italic, sizeof mono_bold_italic };

static const unsigned char mono_bold[] = {
#embed "../resources/ui/fonts/Mono-Bold.ttf.gz"
};
const struct Res_Data adlplug_res_Mono_Bold = { mono_bold, sizeof mono_bold };

static const unsigned char mono_italic[] = {
#embed "../resources/ui/fonts/Mono-Italic.ttf.gz"
};
const struct Res_Data adlplug_res_Mono_Italic = { mono_italic, sizeof mono_italic };

static const unsigned char mono_regular[] = {
#embed "../resources/ui/fonts/Mono-Regular.ttf.gz"
};
const struct Res_Data adlplug_res_Mono_Regular = { mono_regular, sizeof mono_regular };

static const unsigned char sans_bold_italic[] = {
#embed "../resources/ui/fonts/Sans-BoldItalic.ttf.gz"
};
const struct Res_Data adlplug_res_Sans_BoldItalic = { sans_bold_italic, sizeof sans_bold_italic };

static const unsigned char sans_bold[] = {
#embed "../resources/ui/fonts/Sans-Bold.ttf.gz"
};
const struct Res_Data adlplug_res_Sans_Bold = { sans_bold, sizeof sans_bold };

static const unsigned char sans_italic[] = {
#embed "../resources/ui/fonts/Sans-Italic.ttf.gz"
};
const struct Res_Data adlplug_res_Sans_Italic = { sans_italic, sizeof sans_italic };

static const unsigned char sans_regular[] = {
#embed "../resources/ui/fonts/Sans-Regular.ttf.gz"
};
const struct Res_Data adlplug_res_Sans_Regular = { sans_regular, sizeof sans_regular };

static const unsigned char serif_bold_italic[] = {
#embed "../resources/ui/fonts/Serif-BoldItalic.ttf.gz"
};
const struct Res_Data adlplug_res_Serif_BoldItalic = { serif_bold_italic, sizeof serif_bold_italic };

static const unsigned char serif_bold[] = {
#embed "../resources/ui/fonts/Serif-Bold.ttf.gz"
};
const struct Res_Data adlplug_res_Serif_Bold = { serif_bold, sizeof serif_bold };

static const unsigned char serif_italic[] = {
#embed "../resources/ui/fonts/Serif-Italic.ttf.gz"
};
const struct Res_Data adlplug_res_Serif_Italic = { serif_italic, sizeof serif_italic };

static const unsigned char serif_regular[] = {
#embed "../resources/ui/fonts/Serif-Regular.ttf.gz"
};
const struct Res_Data adlplug_res_Serif_Regular = { serif_regular, sizeof serif_regular };
