/*
 * SPDX-FileCopyrightText: 2026 Yuma Kakei <yumasansansan@gmail.com>
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * This file is part of ADLplug-Next. The SPDX lines name its copyright holder
 * and its license, in the machine-readable form of the REUSE specification: the
 * GNU General Public License, version 3 or any later version
 * (LICENSES/GPL-3.0-or-later.txt).
 *
 * Binary resources, embedded at compile time with C23 #embed: the files under
 * resources/, and the pack of instrument banks that tools/bankgen generates in
 * the build directory, which the build adds to the embed path (--embed-dir).
 * resources.h makes them available to C++ as Res::<name>.
 *
 * #embed is a preprocessing directive, so it cannot be generated by a macro;
 * each resource is spelled out. Only the resources of the chip variant being
 * built are embedded. The logos of emulator cores are those whose origin and
 * license are known (REUSE.toml): ADLplug's drawings for Nuke.YKT's cores and,
 * for the OPL3, ESFMu's own logo. The other cores show their name instead.
 */

#include "resources.h"

#if defined(ADLPLUG_OPL3)

static const unsigned char opl3_banks_pak[] = {
#embed <banks.pak>
};
const struct Res_Data adlplug_res_opl3_banks_pak = { opl3_banks_pak, sizeof opl3_banks_pak };

static const unsigned char emu_nuked[] = {
#embed "../resources/ui/cores/Nuked.png"
};
const struct Res_Data adlplug_res_emu_nuked = { emu_nuked, sizeof emu_nuked };

static const unsigned char emu_nuked2[] = {
#embed "../resources/ui/cores/Nuked2.png"
};
const struct Res_Data adlplug_res_emu_nuked2 = { emu_nuked2, sizeof emu_nuked2 };

static const unsigned char emu_esfmu[] = {
#embed "../resources/ui/cores/ESFMu.png"
};
const struct Res_Data adlplug_res_emu_esfmu = { emu_esfmu, sizeof emu_esfmu };

static const unsigned char emoji_u1f4a1[] = {
#embed "../resources/ui/noto-emoji/emoji_u1f4a1.png"
};
const struct Res_Data adlplug_res_emoji_u1f4a1 = { emoji_u1f4a1, sizeof emoji_u1f4a1 };

#elif defined(ADLPLUG_OPN2)

static const unsigned char opn2_banks_pak[] = {
#embed <banks.pak>
};
const struct Res_Data adlplug_res_opn2_banks_pak = { opn2_banks_pak, sizeof opn2_banks_pak };

static const unsigned char emu_nuked[] = {
#embed "../resources/ui/cores/Nuked.png"
};
const struct Res_Data adlplug_res_emu_nuked = { emu_nuked, sizeof emu_nuked };

#endif

static const unsigned char emoji_u1f4be[] = {
#embed "../resources/ui/noto-emoji/emoji_u1f4be.png"
};
const struct Res_Data adlplug_res_emoji_u1f4be = { emoji_u1f4be, sizeof emoji_u1f4be };

static const unsigned char emoji_u1f4c2[] = {
#embed "../resources/ui/noto-emoji/emoji_u1f4c2.png"
};
const struct Res_Data adlplug_res_emoji_u1f4c2 = { emoji_u1f4c2, sizeof emoji_u1f4c2 };

static const unsigned char emoji_u1f4dd[] = {
#embed "../resources/ui/noto-emoji/emoji_u1f4dd.png"
};
const struct Res_Data adlplug_res_emoji_u1f4dd = { emoji_u1f4dd, sizeof emoji_u1f4dd };

static const unsigned char emoji_u2328[] = {
#embed "../resources/ui/noto-emoji/emoji_u2328.png"
};
const struct Res_Data adlplug_res_emoji_u2328 = { emoji_u2328, sizeof emoji_u2328 };

static const unsigned char emoji_u2795[] = {
#embed "../resources/ui/noto-emoji/emoji_u2795.png"
};
const struct Res_Data adlplug_res_emoji_u2795 = { emoji_u2795, sizeof emoji_u2795 };

static const unsigned char knob_skin[] = {
#embed "../resources/ui/knob-skin.png"
};
const struct Res_Data adlplug_res_knob_skin = { knob_skin, sizeof knob_skin };

static const unsigned char slider_skin[] = {
#embed "../resources/ui/slider-skin.png"
};
const struct Res_Data adlplug_res_slider_skin = { slider_skin, sizeof slider_skin };

static const unsigned char mono_bold_italic[] = {
#embed "../resources/ui/fonts/Mono-BoldItalic.ttf.gz"
};
const struct Res_Data adlplug_res_Mono_BoldItalic = { mono_bold_italic, sizeof mono_bold_italic };

static const unsigned char mono_bold[] = {
#embed "../resources/ui/fonts/Mono-Bold.ttf.gz"
};
const struct Res_Data adlplug_res_Mono_Bold = { mono_bold, sizeof mono_bold };

static const unsigned char mono_italic[] = {
#embed "../resources/ui/fonts/Mono-Italic.ttf.gz"
};
const struct Res_Data adlplug_res_Mono_Italic = { mono_italic, sizeof mono_italic };

static const unsigned char mono_regular[] = {
#embed "../resources/ui/fonts/Mono-Regular.ttf.gz"
};
const struct Res_Data adlplug_res_Mono_Regular = { mono_regular, sizeof mono_regular };

static const unsigned char sans_bold_italic[] = {
#embed "../resources/ui/fonts/Sans-BoldItalic.ttf.gz"
};
const struct Res_Data adlplug_res_Sans_BoldItalic = { sans_bold_italic, sizeof sans_bold_italic };

static const unsigned char sans_bold[] = {
#embed "../resources/ui/fonts/Sans-Bold.ttf.gz"
};
const struct Res_Data adlplug_res_Sans_Bold = { sans_bold, sizeof sans_bold };

static const unsigned char sans_italic[] = {
#embed "../resources/ui/fonts/Sans-Italic.ttf.gz"
};
const struct Res_Data adlplug_res_Sans_Italic = { sans_italic, sizeof sans_italic };

static const unsigned char sans_regular[] = {
#embed "../resources/ui/fonts/Sans-Regular.ttf.gz"
};
const struct Res_Data adlplug_res_Sans_Regular = { sans_regular, sizeof sans_regular };

static const unsigned char serif_bold_italic[] = {
#embed "../resources/ui/fonts/Serif-BoldItalic.ttf.gz"
};
const struct Res_Data adlplug_res_Serif_BoldItalic = { serif_bold_italic, sizeof serif_bold_italic };

static const unsigned char serif_bold[] = {
#embed "../resources/ui/fonts/Serif-Bold.ttf.gz"
};
const struct Res_Data adlplug_res_Serif_Bold = { serif_bold, sizeof serif_bold };

static const unsigned char serif_italic[] = {
#embed "../resources/ui/fonts/Serif-Italic.ttf.gz"
};
const struct Res_Data adlplug_res_Serif_Italic = { serif_italic, sizeof serif_italic };

static const unsigned char serif_regular[] = {
#embed "../resources/ui/fonts/Serif-Regular.ttf.gz"
};
const struct Res_Data adlplug_res_Serif_Regular = { serif_regular, sizeof serif_regular };
