# SPDX-FileCopyrightText: 2018 Jean Pierre Cimalando
# SPDX-License-Identifier: BSL-1.0
#
# This file comes from ADLplug, which gave it no notice of its own; it is under
# ADLplug's license, the Boost Software License 1.0 (LICENSES/BSL-1.0.txt). The
# SPDX lines name its copyright holder and license in the machine-readable form
# of the REUSE specification.

# the version of the file specification
configuration-version = 1


[paths]

# the last directory in which instruments have been accessed
last-instrument-directory = 


[piano]

# the default key layout
layout = qwerty

# the QWERTY key map
keymap:qwerty = zsxdcvgbhnjmq2w3er5t6y7ui9o0p

# the QWERTZ key map
keymap:qwertz = ysxdcvgbhnjmq2w3er5t6z7ui9o0p

# the AZERTY key map
keymap:azerty = wsxdcvgbhnj,aéz"er(t-yèuiçoàp
